# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_pb2 as ai__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub:
    """Service Definition

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_unary(
                '/ai.AIService/Generate',
                request_serializer=ai__pb2.GenerateRequest.SerializeToString,
                response_deserializer=ai__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.GenerateStatus = channel.unary_unary(
                '/ai.AIService/GenerateStatus',
                request_serializer=ai__pb2.GenerateStatusRequest.SerializeToString,
                response_deserializer=ai__pb2.GenerateStatusResponse.FromString,
                _registered_method=True)
        self.ConceptImages = channel.unary_unary(
                '/ai.AIService/ConceptImages',
                request_serializer=ai__pb2.ConceptImagesRequest.SerializeToString,
                response_deserializer=ai__pb2.ConceptImagesResponse.FromString,
                _registered_method=True)
        self.DesignChat = channel.unary_unary(
                '/ai.AIService/DesignChat',
                request_serializer=ai__pb2.DesignChatRequest.SerializeToString,
                response_deserializer=ai__pb2.DesignChatResponse.FromString,
                _registered_method=True)
        self.MaintenanceAnalyse = channel.unary_unary(
                '/ai.AIService/MaintenanceAnalyse',
                request_serializer=ai__pb2.MaintenanceAnalyseRequest.SerializeToString,
                response_deserializer=ai__pb2.MaintenanceAnalyseResponse.FromString,
                _registered_method=True)


class AIServiceServicer:
    """Service Definition

    """

    def Generate(self, request, context):
        """3D Generation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConceptImages(self, request, context):
        """Concept Studio
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DesignChat(self, request, context):
        """Design workspace chat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MaintenanceAnalyse(self, request, context):
        """Predictive maintenance analysis
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=ai__pb2.GenerateRequest.FromString,
                    response_serializer=ai__pb2.GenerateResponse.SerializeToString,
            ),
            'GenerateStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateStatus,
                    request_deserializer=ai__pb2.GenerateStatusRequest.FromString,
                    response_serializer=ai__pb2.GenerateStatusResponse.SerializeToString,
            ),
            'ConceptImages': grpc.unary_unary_rpc_method_handler(
                    servicer.ConceptImages,
                    request_deserializer=ai__pb2.ConceptImagesRequest.FromString,
                    response_serializer=ai__pb2.ConceptImagesResponse.SerializeToString,
            ),
            'DesignChat': grpc.unary_unary_rpc_method_handler(
                    servicer.DesignChat,
                    request_deserializer=ai__pb2.DesignChatRequest.FromString,
                    response_serializer=ai__pb2.DesignChatResponse.SerializeToString,
            ),
            'MaintenanceAnalyse': grpc.unary_unary_rpc_method_handler(
                    servicer.MaintenanceAnalyse,
                    request_deserializer=ai__pb2.MaintenanceAnalyseRequest.FromString,
                    response_serializer=ai__pb2.MaintenanceAnalyseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService:
    """Service Definition

    """

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/Generate',
            ai__pb2.GenerateRequest.SerializeToString,
            ai__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/GenerateStatus',
            ai__pb2.GenerateStatusRequest.SerializeToString,
            ai__pb2.GenerateStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConceptImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/ConceptImages',
            ai__pb2.ConceptImagesRequest.SerializeToString,
            ai__pb2.ConceptImagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DesignChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/DesignChat',
            ai__pb2.DesignChatRequest.SerializeToString,
            ai__pb2.DesignChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MaintenanceAnalyse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/MaintenanceAnalyse',
            ai__pb2.MaintenanceAnalyseRequest.SerializeToString,
            ai__pb2.MaintenanceAnalyseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
