// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: ai.proto

package aipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChatMessage is used for conversation history on every AI call.
// AI APIs are stateless — Go reads last 10 rows from DB and sends them here.
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // "user" | "assistant"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GenerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`                         // "text_to_model" | "image_to_model"
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`                     // used when mode = text_to_model
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"` // used when mode = image_to_model (S3 URL, never raw bytes)
	ChatId        string                 `protobuf:"bytes,4,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,5,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *GenerateRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenerateRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *GenerateRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *GenerateRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type GenerateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"` // external provider job ID (Meshy / Tripo3D)
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`            // always "processing" on initial response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GenerateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GenerateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateStatusRequest) Reset() {
	*x = GenerateStatusRequest{}
	mi := &file_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateStatusRequest) ProtoMessage() {}

func (x *GenerateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateStatusRequest.ProtoReflect.Descriptor instead.
func (*GenerateStatusRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GenerateStatusRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type GenerateStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`                     // "processing" | "done" | "failed"
	ModelUrl      string                 `protobuf:"bytes,2,opt,name=model_url,json=modelUrl,proto3" json:"model_url,omitempty"` // S3 URL of .glb file — only populated when status = "done"
	ChatId        string                 `protobuf:"bytes,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateStatusResponse) Reset() {
	*x = GenerateStatusResponse{}
	mi := &file_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateStatusResponse) ProtoMessage() {}

func (x *GenerateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateStatusResponse.ProtoReflect.Descriptor instead.
func (*GenerateStatusResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GenerateStatusResponse) GetModelUrl() string {
	if x != nil {
		return x.ModelUrl
	}
	return ""
}

func (x *GenerateStatusResponse) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type ConceptImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ChatId        string                 `protobuf:"bytes,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConceptImagesRequest) Reset() {
	*x = ConceptImagesRequest{}
	mi := &file_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConceptImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConceptImagesRequest) ProtoMessage() {}

func (x *ConceptImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConceptImagesRequest.ProtoReflect.Descriptor instead.
func (*ConceptImagesRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{5}
}

func (x *ConceptImagesRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ConceptImagesRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ConceptImagesRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type ConceptImagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// repeated = Go slice []string — one URL per concept image
	Images        []string `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"` // 4 S3 URLs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConceptImagesResponse) Reset() {
	*x = ConceptImagesResponse{}
	mi := &file_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConceptImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConceptImagesResponse) ProtoMessage() {}

func (x *ConceptImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConceptImagesResponse.ProtoReflect.Descriptor instead.
func (*ConceptImagesResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{6}
}

func (x *ConceptImagesResponse) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type DesignChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Last 10 messages from workspace_chats DB table (for AI memory)
	History       []*ChatMessage `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	Prompt        string         `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`                        // The user's new message
	SceneJson     string         `protobuf:"bytes,3,opt,name=scene_json,json=sceneJson,proto3" json:"scene_json,omitempty"` // Full 3D scene JSONB serialised as a string
	WorkspaceId   string         `protobuf:"bytes,4,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ChatId        string         `protobuf:"bytes,5,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DesignChatRequest) Reset() {
	*x = DesignChatRequest{}
	mi := &file_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesignChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesignChatRequest) ProtoMessage() {}

func (x *DesignChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesignChatRequest.ProtoReflect.Descriptor instead.
func (*DesignChatRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{7}
}

func (x *DesignChatRequest) GetHistory() []*ChatMessage {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *DesignChatRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *DesignChatRequest) GetSceneJson() string {
	if x != nil {
		return x.SceneJson
	}
	return ""
}

func (x *DesignChatRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *DesignChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type DesignChatResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Type             string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                                   // "text" | "model_gen"
	Content          string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                                             // AI reply text
	FollowUpQuestion string                 `protobuf:"bytes,3,opt,name=follow_up_question,json=followUpQuestion,proto3" json:"follow_up_question,omitempty"` // optional — AI may ask a follow-up question
	JobId            string                 `protobuf:"bytes,4,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`                                    // only set when type = "model_gen"
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DesignChatResponse) Reset() {
	*x = DesignChatResponse{}
	mi := &file_ai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesignChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesignChatResponse) ProtoMessage() {}

func (x *DesignChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesignChatResponse.ProtoReflect.Descriptor instead.
func (*DesignChatResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{8}
}

func (x *DesignChatResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DesignChatResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DesignChatResponse) GetFollowUpQuestion() string {
	if x != nil {
		return x.FollowUpQuestion
	}
	return ""
}

func (x *DesignChatResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type MaintenanceAnalyseRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ManagementId string                 `protobuf:"bytes,1,opt,name=management_id,json=managementId,proto3" json:"management_id,omitempty"`
	VehicleType  string                 `protobuf:"bytes,2,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"` // "DRONE" | "AIRCRAFT" | "FIGHTER_JET" | "OTHER"
	// Last N messages from management_chats DB table
	History            []*ChatMessage `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
	Prompt             string         `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`                                                     // User's question / instruction
	AttachmentText     string         `protobuf:"bytes,5,opt,name=attachment_text,json=attachmentText,proto3" json:"attachment_text,omitempty"`               // CSV/PDF text extracted by Go (never raw file)
	PreviousSensorData string         `protobuf:"bytes,6,opt,name=previous_sensor_data,json=previousSensorData,proto3" json:"previous_sensor_data,omitempty"` // Latest sensor_data JSONB from management table
	ChatId             string         `protobuf:"bytes,7,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MaintenanceAnalyseRequest) Reset() {
	*x = MaintenanceAnalyseRequest{}
	mi := &file_ai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenanceAnalyseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenanceAnalyseRequest) ProtoMessage() {}

func (x *MaintenanceAnalyseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintenanceAnalyseRequest.ProtoReflect.Descriptor instead.
func (*MaintenanceAnalyseRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{9}
}

func (x *MaintenanceAnalyseRequest) GetManagementId() string {
	if x != nil {
		return x.ManagementId
	}
	return ""
}

func (x *MaintenanceAnalyseRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *MaintenanceAnalyseRequest) GetHistory() []*ChatMessage {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *MaintenanceAnalyseRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *MaintenanceAnalyseRequest) GetAttachmentText() string {
	if x != nil {
		return x.AttachmentText
	}
	return ""
}

func (x *MaintenanceAnalyseRequest) GetPreviousSensorData() string {
	if x != nil {
		return x.PreviousSensorData
	}
	return ""
}

func (x *MaintenanceAnalyseRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type MaintenanceAnalyseResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Content          string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`                                           // Human-readable analysis text
	AnalysisSnapshot string                 `protobuf:"bytes,2,opt,name=analysis_snapshot,json=analysisSnapshot,proto3" json:"analysis_snapshot,omitempty"` // Full structured JSON — Go writes to management.analysis_result
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MaintenanceAnalyseResponse) Reset() {
	*x = MaintenanceAnalyseResponse{}
	mi := &file_ai_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenanceAnalyseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenanceAnalyseResponse) ProtoMessage() {}

func (x *MaintenanceAnalyseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintenanceAnalyseResponse.ProtoReflect.Descriptor instead.
func (*MaintenanceAnalyseResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{10}
}

func (x *MaintenanceAnalyseResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MaintenanceAnalyseResponse) GetAnalysisSnapshot() string {
	if x != nil {
		return x.AnalysisSnapshot
	}
	return ""
}

var File_ai_proto protoreflect.FileDescriptor

const file_ai_proto_rawDesc = "" +
	"\n" +
	"\bai.proto\x12\x02ai\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x96\x01\n" +
	"\x0fGenerateRequest\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12\x17\n" +
	"\achat_id\x18\x04 \x01(\tR\x06chatId\x12!\n" +
	"\fworkspace_id\x18\x05 \x01(\tR\vworkspaceId\"A\n" +
	"\x10GenerateResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"G\n" +
	"\x15GenerateStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\"f\n" +
	"\x16GenerateStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1b\n" +
	"\tmodel_url\x18\x02 \x01(\tR\bmodelUrl\x12\x17\n" +
	"\achat_id\x18\x03 \x01(\tR\x06chatId\"j\n" +
	"\x14ConceptImagesRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\achat_id\x18\x03 \x01(\tR\x06chatId\"/\n" +
	"\x15ConceptImagesResponse\x12\x16\n" +
	"\x06images\x18\x01 \x03(\tR\x06images\"\xb1\x01\n" +
	"\x11DesignChatRequest\x12)\n" +
	"\ahistory\x18\x01 \x03(\v2\x0f.ai.ChatMessageR\ahistory\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x1d\n" +
	"\n" +
	"scene_json\x18\x03 \x01(\tR\tsceneJson\x12!\n" +
	"\fworkspace_id\x18\x04 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\achat_id\x18\x05 \x01(\tR\x06chatId\"\x87\x01\n" +
	"\x12DesignChatResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12,\n" +
	"\x12follow_up_question\x18\x03 \x01(\tR\x10followUpQuestion\x12\x15\n" +
	"\x06job_id\x18\x04 \x01(\tR\x05jobId\"\x9a\x02\n" +
	"\x19MaintenanceAnalyseRequest\x12#\n" +
	"\rmanagement_id\x18\x01 \x01(\tR\fmanagementId\x12!\n" +
	"\fvehicle_type\x18\x02 \x01(\tR\vvehicleType\x12)\n" +
	"\ahistory\x18\x03 \x03(\v2\x0f.ai.ChatMessageR\ahistory\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12'\n" +
	"\x0fattachment_text\x18\x05 \x01(\tR\x0eattachmentText\x120\n" +
	"\x14previous_sensor_data\x18\x06 \x01(\tR\x12previousSensorData\x12\x17\n" +
	"\achat_id\x18\a \x01(\tR\x06chatId\"c\n" +
	"\x1aMaintenanceAnalyseResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12+\n" +
	"\x11analysis_snapshot\x18\x02 \x01(\tR\x10analysisSnapshot2\xe3\x02\n" +
	"\tAIService\x125\n" +
	"\bGenerate\x12\x13.ai.GenerateRequest\x1a\x14.ai.GenerateResponse\x12G\n" +
	"\x0eGenerateStatus\x12\x19.ai.GenerateStatusRequest\x1a\x1a.ai.GenerateStatusResponse\x12D\n" +
	"\rConceptImages\x12\x18.ai.ConceptImagesRequest\x1a\x19.ai.ConceptImagesResponse\x12;\n" +
	"\n" +
	"DesignChat\x12\x15.ai.DesignChatRequest\x1a\x16.ai.DesignChatResponse\x12S\n" +
	"\x12MaintenanceAnalyse\x12\x1d.ai.MaintenanceAnalyseRequest\x1a\x1e.ai.MaintenanceAnalyseResponseB2Z0github.com/wakeupguruu/airix/internal/pb/ai;aipbb\x06proto3"

var (
	file_ai_proto_rawDescOnce sync.Once
	file_ai_proto_rawDescData []byte
)

func file_ai_proto_rawDescGZIP() []byte {
	file_ai_proto_rawDescOnce.Do(func() {
		file_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)))
	})
	return file_ai_proto_rawDescData
}

var file_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_ai_proto_goTypes = []any{
	(*ChatMessage)(nil),                // 0: ai.ChatMessage
	(*GenerateRequest)(nil),            // 1: ai.GenerateRequest
	(*GenerateResponse)(nil),           // 2: ai.GenerateResponse
	(*GenerateStatusRequest)(nil),      // 3: ai.GenerateStatusRequest
	(*GenerateStatusResponse)(nil),     // 4: ai.GenerateStatusResponse
	(*ConceptImagesRequest)(nil),       // 5: ai.ConceptImagesRequest
	(*ConceptImagesResponse)(nil),      // 6: ai.ConceptImagesResponse
	(*DesignChatRequest)(nil),          // 7: ai.DesignChatRequest
	(*DesignChatResponse)(nil),         // 8: ai.DesignChatResponse
	(*MaintenanceAnalyseRequest)(nil),  // 9: ai.MaintenanceAnalyseRequest
	(*MaintenanceAnalyseResponse)(nil), // 10: ai.MaintenanceAnalyseResponse
}
var file_ai_proto_depIdxs = []int32{
	0,  // 0: ai.DesignChatRequest.history:type_name -> ai.ChatMessage
	0,  // 1: ai.MaintenanceAnalyseRequest.history:type_name -> ai.ChatMessage
	1,  // 2: ai.AIService.Generate:input_type -> ai.GenerateRequest
	3,  // 3: ai.AIService.GenerateStatus:input_type -> ai.GenerateStatusRequest
	5,  // 4: ai.AIService.ConceptImages:input_type -> ai.ConceptImagesRequest
	7,  // 5: ai.AIService.DesignChat:input_type -> ai.DesignChatRequest
	9,  // 6: ai.AIService.MaintenanceAnalyse:input_type -> ai.MaintenanceAnalyseRequest
	2,  // 7: ai.AIService.Generate:output_type -> ai.GenerateResponse
	4,  // 8: ai.AIService.GenerateStatus:output_type -> ai.GenerateStatusResponse
	6,  // 9: ai.AIService.ConceptImages:output_type -> ai.ConceptImagesResponse
	8,  // 10: ai.AIService.DesignChat:output_type -> ai.DesignChatResponse
	10, // 11: ai.AIService.MaintenanceAnalyse:output_type -> ai.MaintenanceAnalyseResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_ai_proto_init() }
func file_ai_proto_init() {
	if File_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_proto_goTypes,
		DependencyIndexes: file_ai_proto_depIdxs,
		MessageInfos:      file_ai_proto_msgTypes,
	}.Build()
	File_ai_proto = out.File
	file_ai_proto_goTypes = nil
	file_ai_proto_depIdxs = nil
}
