// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: ai.proto

package aipb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIService_Generate_FullMethodName           = "/ai.AIService/Generate"
	AIService_GenerateStatus_FullMethodName     = "/ai.AIService/GenerateStatus"
	AIService_ConceptImages_FullMethodName      = "/ai.AIService/ConceptImages"
	AIService_DesignChat_FullMethodName         = "/ai.AIService/DesignChat"
	AIService_MaintenanceAnalyse_FullMethodName = "/ai.AIService/MaintenanceAnalyse"
)

// AIServiceClient is the client API for AIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIServiceClient interface {
	// 3D Generation
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error)
	GenerateStatus(ctx context.Context, in *GenerateStatusRequest, opts ...grpc.CallOption) (*GenerateStatusResponse, error)
	// Concept Studio
	ConceptImages(ctx context.Context, in *ConceptImagesRequest, opts ...grpc.CallOption) (*ConceptImagesResponse, error)
	// Design workspace chat
	DesignChat(ctx context.Context, in *DesignChatRequest, opts ...grpc.CallOption) (*DesignChatResponse, error)
	// Predictive maintenance analysis
	MaintenanceAnalyse(ctx context.Context, in *MaintenanceAnalyseRequest, opts ...grpc.CallOption) (*MaintenanceAnalyseResponse, error)
}

type aIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIServiceClient(cc grpc.ClientConnInterface) AIServiceClient {
	return &aIServiceClient{cc}
}

func (c *aIServiceClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateResponse)
	err := c.cc.Invoke(ctx, AIService_Generate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) GenerateStatus(ctx context.Context, in *GenerateStatusRequest, opts ...grpc.CallOption) (*GenerateStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateStatusResponse)
	err := c.cc.Invoke(ctx, AIService_GenerateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) ConceptImages(ctx context.Context, in *ConceptImagesRequest, opts ...grpc.CallOption) (*ConceptImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConceptImagesResponse)
	err := c.cc.Invoke(ctx, AIService_ConceptImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) DesignChat(ctx context.Context, in *DesignChatRequest, opts ...grpc.CallOption) (*DesignChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesignChatResponse)
	err := c.cc.Invoke(ctx, AIService_DesignChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) MaintenanceAnalyse(ctx context.Context, in *MaintenanceAnalyseRequest, opts ...grpc.CallOption) (*MaintenanceAnalyseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaintenanceAnalyseResponse)
	err := c.cc.Invoke(ctx, AIService_MaintenanceAnalyse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIServiceServer is the server API for AIService service.
// All implementations must embed UnimplementedAIServiceServer
// for forward compatibility.
type AIServiceServer interface {
	// 3D Generation
	Generate(context.Context, *GenerateRequest) (*GenerateResponse, error)
	GenerateStatus(context.Context, *GenerateStatusRequest) (*GenerateStatusResponse, error)
	// Concept Studio
	ConceptImages(context.Context, *ConceptImagesRequest) (*ConceptImagesResponse, error)
	// Design workspace chat
	DesignChat(context.Context, *DesignChatRequest) (*DesignChatResponse, error)
	// Predictive maintenance analysis
	MaintenanceAnalyse(context.Context, *MaintenanceAnalyseRequest) (*MaintenanceAnalyseResponse, error)
	mustEmbedUnimplementedAIServiceServer()
}

// UnimplementedAIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIServiceServer struct{}

func (UnimplementedAIServiceServer) Generate(context.Context, *GenerateRequest) (*GenerateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedAIServiceServer) GenerateStatus(context.Context, *GenerateStatusRequest) (*GenerateStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateStatus not implemented")
}
func (UnimplementedAIServiceServer) ConceptImages(context.Context, *ConceptImagesRequest) (*ConceptImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConceptImages not implemented")
}
func (UnimplementedAIServiceServer) DesignChat(context.Context, *DesignChatRequest) (*DesignChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DesignChat not implemented")
}
func (UnimplementedAIServiceServer) MaintenanceAnalyse(context.Context, *MaintenanceAnalyseRequest) (*MaintenanceAnalyseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MaintenanceAnalyse not implemented")
}
func (UnimplementedAIServiceServer) mustEmbedUnimplementedAIServiceServer() {}
func (UnimplementedAIServiceServer) testEmbeddedByValue()                   {}

// UnsafeAIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIServiceServer will
// result in compilation errors.
type UnsafeAIServiceServer interface {
	mustEmbedUnimplementedAIServiceServer()
}

func RegisterAIServiceServer(s grpc.ServiceRegistrar, srv AIServiceServer) {
	// If the following call panics, it indicates UnimplementedAIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIService_ServiceDesc, srv)
}

func _AIService_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_Generate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).Generate(ctx, req.(*GenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_GenerateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).GenerateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_GenerateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).GenerateStatus(ctx, req.(*GenerateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_ConceptImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConceptImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).ConceptImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_ConceptImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).ConceptImages(ctx, req.(*ConceptImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_DesignChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesignChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).DesignChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_DesignChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).DesignChat(ctx, req.(*DesignChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_MaintenanceAnalyse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaintenanceAnalyseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).MaintenanceAnalyse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_MaintenanceAnalyse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).MaintenanceAnalyse(ctx, req.(*MaintenanceAnalyseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIService_ServiceDesc is the grpc.ServiceDesc for AIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.AIService",
	HandlerType: (*AIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _AIService_Generate_Handler,
		},
		{
			MethodName: "GenerateStatus",
			Handler:    _AIService_GenerateStatus_Handler,
		},
		{
			MethodName: "ConceptImages",
			Handler:    _AIService_ConceptImages_Handler,
		},
		{
			MethodName: "DesignChat",
			Handler:    _AIService_DesignChat_Handler,
		},
		{
			MethodName: "MaintenanceAnalyse",
			Handler:    _AIService_MaintenanceAnalyse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai.proto",
}
