// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: management_chats.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createManagementChat = `-- name: CreateManagementChat :one
INSERT INTO management_chats (management_id, user_id, role, type, content, status, attachment_url, attachment_text)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, management_id, user_id, role, type, content, status, analysis_snapshot, attachment_url, attachment_text, created_at
`

type CreateManagementChatParams struct {
	ManagementID   uuid.UUID   `json:"management_id"`
	UserID         uuid.UUID   `json:"user_id"`
	Role           string      `json:"role"`
	Type           string      `json:"type"`
	Content        string      `json:"content"`
	Status         pgtype.Text `json:"status"`
	AttachmentUrl  pgtype.Text `json:"attachment_url"`
	AttachmentText pgtype.Text `json:"attachment_text"`
}

func (q *Queries) CreateManagementChat(ctx context.Context, arg CreateManagementChatParams) (ManagementChat, error) {
	row := q.db.QueryRow(ctx, createManagementChat,
		arg.ManagementID,
		arg.UserID,
		arg.Role,
		arg.Type,
		arg.Content,
		arg.Status,
		arg.AttachmentUrl,
		arg.AttachmentText,
	)
	var i ManagementChat
	err := row.Scan(
		&i.ID,
		&i.ManagementID,
		&i.UserID,
		&i.Role,
		&i.Type,
		&i.Content,
		&i.Status,
		&i.AnalysisSnapshot,
		&i.AttachmentUrl,
		&i.AttachmentText,
		&i.CreatedAt,
	)
	return i, err
}

const getManagementChatsByManagementID = `-- name: GetManagementChatsByManagementID :many
SELECT id, management_id, user_id, role, type, content, status, analysis_snapshot, attachment_url, attachment_text, created_at FROM management_chats
WHERE management_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetManagementChatsByManagementID(ctx context.Context, managementID uuid.UUID) ([]ManagementChat, error) {
	rows, err := q.db.Query(ctx, getManagementChatsByManagementID, managementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManagementChat
	for rows.Next() {
		var i ManagementChat
		if err := rows.Scan(
			&i.ID,
			&i.ManagementID,
			&i.UserID,
			&i.Role,
			&i.Type,
			&i.Content,
			&i.Status,
			&i.AnalysisSnapshot,
			&i.AttachmentUrl,
			&i.AttachmentText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateManagementChatStatus = `-- name: UpdateManagementChatStatus :one
UPDATE management_chats
SET
    status            = $2,
    content           = $3,
    analysis_snapshot = $4
WHERE id = $1
RETURNING id, management_id, user_id, role, type, content, status, analysis_snapshot, attachment_url, attachment_text, created_at
`

type UpdateManagementChatStatusParams struct {
	ID               uuid.UUID   `json:"id"`
	Status           pgtype.Text `json:"status"`
	Content          string      `json:"content"`
	AnalysisSnapshot []byte      `json:"analysis_snapshot"`
}

func (q *Queries) UpdateManagementChatStatus(ctx context.Context, arg UpdateManagementChatStatusParams) (ManagementChat, error) {
	row := q.db.QueryRow(ctx, updateManagementChatStatus,
		arg.ID,
		arg.Status,
		arg.Content,
		arg.AnalysisSnapshot,
	)
	var i ManagementChat
	err := row.Scan(
		&i.ID,
		&i.ManagementID,
		&i.UserID,
		&i.Role,
		&i.Type,
		&i.Content,
		&i.Status,
		&i.AnalysisSnapshot,
		&i.AttachmentUrl,
		&i.AttachmentText,
		&i.CreatedAt,
	)
	return i, err
}
