// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: management.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countManagementsFiltered = `-- name: CountManagementsFiltered :one
SELECT COUNT(*) FROM management
WHERE user_id = $1
  AND ($2::TEXT   IS NULL OR type = $2::TEXT)
  AND ($3::TEXT IS NULL OR name ILIKE '%' || $3::TEXT || '%')
`

type CountManagementsFilteredParams struct {
	UserID uuid.UUID   `json:"user_id"`
	Type   pgtype.Text `json:"type"`
	Search pgtype.Text `json:"search"`
}

func (q *Queries) CountManagementsFiltered(ctx context.Context, arg CountManagementsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countManagementsFiltered, arg.UserID, arg.Type, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createManagement = `-- name: CreateManagement :one
INSERT INTO management (user_id, name, description, type, image_url, sensor_data)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, description, type, image_url, sensor_data, analysis_result, created_at, updated_at
`

type CreateManagementParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Type        string      `json:"type"`
	ImageUrl    pgtype.Text `json:"image_url"`
	SensorData  []byte      `json:"sensor_data"`
}

func (q *Queries) CreateManagement(ctx context.Context, arg CreateManagementParams) (Management, error) {
	row := q.db.QueryRow(ctx, createManagement,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.ImageUrl,
		arg.SensorData,
	)
	var i Management
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.ImageUrl,
		&i.SensorData,
		&i.AnalysisResult,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteManagement = `-- name: DeleteManagement :exec
DELETE FROM management WHERE id = $1
`

func (q *Queries) DeleteManagement(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteManagement, id)
	return err
}

const getManagementByID = `-- name: GetManagementByID :one
SELECT id, user_id, name, description, type, image_url, sensor_data, analysis_result, created_at, updated_at FROM management WHERE id = $1
`

func (q *Queries) GetManagementByID(ctx context.Context, id uuid.UUID) (Management, error) {
	row := q.db.QueryRow(ctx, getManagementByID, id)
	var i Management
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.ImageUrl,
		&i.SensorData,
		&i.AnalysisResult,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getManagementsFiltered = `-- name: GetManagementsFiltered :many
SELECT id, user_id, name, description, type, image_url, sensor_data, analysis_result, created_at, updated_at FROM management
WHERE user_id = $1
  AND ($2::TEXT   IS NULL OR type = $2::TEXT)
  AND ($3::TEXT IS NULL OR name ILIKE '%' || $3::TEXT || '%')
ORDER BY created_at DESC
LIMIT  $5
OFFSET $4
`

type GetManagementsFilteredParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	Type      pgtype.Text `json:"type"`
	Search    pgtype.Text `json:"search"`
	OffsetVal int32       `json:"offset_val"`
	LimitVal  int32       `json:"limit_val"`
}

func (q *Queries) GetManagementsFiltered(ctx context.Context, arg GetManagementsFilteredParams) ([]Management, error) {
	rows, err := q.db.Query(ctx, getManagementsFiltered,
		arg.UserID,
		arg.Type,
		arg.Search,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Management
	for rows.Next() {
		var i Management
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.ImageUrl,
			&i.SensorData,
			&i.AnalysisResult,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateManagement = `-- name: UpdateManagement :one
UPDATE management
SET
    name        = $2,
    description = $3,
    image_url   = $4,
    updated_at  = NOW()
WHERE id = $1
RETURNING id, user_id, name, description, type, image_url, sensor_data, analysis_result, created_at, updated_at
`

type UpdateManagementParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ImageUrl    pgtype.Text `json:"image_url"`
}

func (q *Queries) UpdateManagement(ctx context.Context, arg UpdateManagementParams) (Management, error) {
	row := q.db.QueryRow(ctx, updateManagement,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
	)
	var i Management
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.ImageUrl,
		&i.SensorData,
		&i.AnalysisResult,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateManagementAnalysis = `-- name: UpdateManagementAnalysis :one
UPDATE management
SET
    sensor_data     = $2,
    analysis_result = $3,
    updated_at      = NOW()
WHERE id = $1
RETURNING id, user_id, name, description, type, image_url, sensor_data, analysis_result, created_at, updated_at
`

type UpdateManagementAnalysisParams struct {
	ID             uuid.UUID `json:"id"`
	SensorData     []byte    `json:"sensor_data"`
	AnalysisResult []byte    `json:"analysis_result"`
}

func (q *Queries) UpdateManagementAnalysis(ctx context.Context, arg UpdateManagementAnalysisParams) (Management, error) {
	row := q.db.QueryRow(ctx, updateManagementAnalysis, arg.ID, arg.SensorData, arg.AnalysisResult)
	var i Management
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.ImageUrl,
		&i.SensorData,
		&i.AnalysisResult,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
