// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Management struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	Type           string             `json:"type"`
	ImageUrl       pgtype.Text        `json:"image_url"`
	SensorData     []byte             `json:"sensor_data"`
	AnalysisResult []byte             `json:"analysis_result"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ManagementChat struct {
	ID               uuid.UUID          `json:"id"`
	ManagementID     uuid.UUID          `json:"management_id"`
	UserID           uuid.UUID          `json:"user_id"`
	Role             string             `json:"role"`
	Type             string             `json:"type"`
	Content          string             `json:"content"`
	Status           pgtype.Text        `json:"status"`
	AnalysisSnapshot []byte             `json:"analysis_snapshot"`
	AttachmentUrl    pgtype.Text        `json:"attachment_url"`
	AttachmentText   pgtype.Text        `json:"attachment_text"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Setting struct {
	ID                   uuid.UUID          `json:"id"`
	UserID               uuid.UUID          `json:"user_id"`
	Theme                string             `json:"theme"`
	AutoSave             bool               `json:"auto_save"`
	NotificationsEnabled bool               `json:"notifications_enabled"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID            uuid.UUID          `json:"id"`
	Username      string             `json:"username"`
	FullName      pgtype.Text        `json:"full_name"`
	Email         string             `json:"email"`
	ContactNumber pgtype.Text        `json:"contact_number"`
	Password      pgtype.Text        `json:"password"`
	GoogleID      pgtype.Text        `json:"google_id"`
	ProfileImage  pgtype.Text        `json:"profile_image"`
	Plan          string             `json:"plan"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Workspace struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	Status    string             `json:"status"`
	SceneJson []byte             `json:"scene_json"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceChat struct {
	ID            uuid.UUID          `json:"id"`
	WorkspaceID   uuid.UUID          `json:"workspace_id"`
	UserID        uuid.UUID          `json:"user_id"`
	Role          string             `json:"role"`
	Type          string             `json:"type"`
	Content       string             `json:"content"`
	ImageUrl      pgtype.Text        `json:"image_url"`
	ModelSnapshot []byte             `json:"model_snapshot"`
	JobID         pgtype.Text        `json:"job_id"`
	ResultModelID pgtype.UUID        `json:"result_model_id"`
	Status        pgtype.Text        `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type WorkspaceModel struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Name        pgtype.Text        `json:"name"`
	S3Url       string             `json:"s3_url"`
	Source      string             `json:"source"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
