// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const createSettings = `-- name: CreateSettings :one
INSERT INTO settings (user_id, theme, auto_save, notifications_enabled)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, theme, auto_save, notifications_enabled, updated_at
`

type CreateSettingsParams struct {
	UserID               uuid.UUID `json:"user_id"`
	Theme                string    `json:"theme"`
	AutoSave             bool      `json:"auto_save"`
	NotificationsEnabled bool      `json:"notifications_enabled"`
}

func (q *Queries) CreateSettings(ctx context.Context, arg CreateSettingsParams) (Setting, error) {
	row := q.db.QueryRow(ctx, createSettings,
		arg.UserID,
		arg.Theme,
		arg.AutoSave,
		arg.NotificationsEnabled,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Theme,
		&i.AutoSave,
		&i.NotificationsEnabled,
		&i.UpdatedAt,
	)
	return i, err
}

const getSettingsByUserID = `-- name: GetSettingsByUserID :one
SELECT id, user_id, theme, auto_save, notifications_enabled, updated_at FROM settings WHERE user_id = $1
`

func (q *Queries) GetSettingsByUserID(ctx context.Context, userID uuid.UUID) (Setting, error) {
	row := q.db.QueryRow(ctx, getSettingsByUserID, userID)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Theme,
		&i.AutoSave,
		&i.NotificationsEnabled,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSettings = `-- name: UpdateSettings :one
UPDATE settings
SET
    theme                 = $2,
    auto_save             = $3,
    notifications_enabled = $4,
    updated_at            = NOW()
WHERE user_id = $1
RETURNING id, user_id, theme, auto_save, notifications_enabled, updated_at
`

type UpdateSettingsParams struct {
	UserID               uuid.UUID `json:"user_id"`
	Theme                string    `json:"theme"`
	AutoSave             bool      `json:"auto_save"`
	NotificationsEnabled bool      `json:"notifications_enabled"`
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (Setting, error) {
	row := q.db.QueryRow(ctx, updateSettings,
		arg.UserID,
		arg.Theme,
		arg.AutoSave,
		arg.NotificationsEnabled,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Theme,
		&i.AutoSave,
		&i.NotificationsEnabled,
		&i.UpdatedAt,
	)
	return i, err
}
