// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, full_name, email, contact_number, password, google_id, profile_image, plan)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, username, full_name, email, contact_number, password, google_id, profile_image, plan, created_at, updated_at
`

type CreateUserParams struct {
	Username      string      `json:"username"`
	FullName      pgtype.Text `json:"full_name"`
	Email         string      `json:"email"`
	ContactNumber pgtype.Text `json:"contact_number"`
	Password      pgtype.Text `json:"password"`
	GoogleID      pgtype.Text `json:"google_id"`
	ProfileImage  pgtype.Text `json:"profile_image"`
	Plan          string      `json:"plan"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.FullName,
		arg.Email,
		arg.ContactNumber,
		arg.Password,
		arg.GoogleID,
		arg.ProfileImage,
		arg.Plan,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.ContactNumber,
		&i.Password,
		&i.GoogleID,
		&i.ProfileImage,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, full_name, email, contact_number, password, google_id, profile_image, plan, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.ContactNumber,
		&i.Password,
		&i.GoogleID,
		&i.ProfileImage,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, full_name, email, contact_number, password, google_id, profile_image, plan, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.ContactNumber,
		&i.Password,
		&i.GoogleID,
		&i.ProfileImage,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, full_name, email, contact_number, password, google_id, profile_image, plan, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.ContactNumber,
		&i.Password,
		&i.GoogleID,
		&i.ProfileImage,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    full_name      = $2,
    contact_number = $3,
    profile_image  = $4,
    updated_at     = NOW()
WHERE id = $1
RETURNING id, username, full_name, email, contact_number, password, google_id, profile_image, plan, created_at, updated_at
`

type UpdateUserParams struct {
	ID            uuid.UUID   `json:"id"`
	FullName      pgtype.Text `json:"full_name"`
	ContactNumber pgtype.Text `json:"contact_number"`
	ProfileImage  pgtype.Text `json:"profile_image"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FullName,
		arg.ContactNumber,
		arg.ProfileImage,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.ContactNumber,
		&i.Password,
		&i.GoogleID,
		&i.ProfileImage,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET
    password   = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID       uuid.UUID   `json:"id"`
	Password pgtype.Text `json:"password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.Password)
	return err
}

const updateUserPlan = `-- name: UpdateUserPlan :one
UPDATE users
SET
    plan       = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, username, full_name, email, contact_number, password, google_id, profile_image, plan, created_at, updated_at
`

type UpdateUserPlanParams struct {
	ID   uuid.UUID `json:"id"`
	Plan string    `json:"plan"`
}

func (q *Queries) UpdateUserPlan(ctx context.Context, arg UpdateUserPlanParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPlan, arg.ID, arg.Plan)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.ContactNumber,
		&i.Password,
		&i.GoogleID,
		&i.ProfileImage,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
