// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countWorkspacesFiltered = `-- name: CountWorkspacesFiltered :one
SELECT COUNT(*) FROM workspaces
WHERE user_id = $1
  AND ($2::TEXT    IS NULL OR type   = $2::TEXT)
  AND ($3::TEXT  IS NULL OR status = $3::TEXT)
  AND ($4::TEXT  IS NULL OR name   ILIKE '%' || $4::TEXT || '%')
`

type CountWorkspacesFilteredParams struct {
	UserID uuid.UUID   `json:"user_id"`
	Type   pgtype.Text `json:"type"`
	Status pgtype.Text `json:"status"`
	Search pgtype.Text `json:"search"`
}

// Needed for pagination: total count with same filters as GetWorkspacesFiltered
func (q *Queries) CountWorkspacesFiltered(ctx context.Context, arg CountWorkspacesFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkspacesFiltered,
		arg.UserID,
		arg.Type,
		arg.Status,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (user_id, name, type, status, scene_json)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, type, status, scene_json, created_at, updated_at
`

type CreateWorkspaceParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Name      string    `json:"name"`
	Type      string    `json:"type"`
	Status    string    `json:"status"`
	SceneJson []byte    `json:"scene_json"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Status,
		arg.SceneJson,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.SceneJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces WHERE id = $1
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkspace, id)
	return err
}

const getRecentWorkspaces = `-- name: GetRecentWorkspaces :many
SELECT id, user_id, name, type, status, scene_json, created_at, updated_at FROM workspaces
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetRecentWorkspacesParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

// Used on the workspace dashboard — shows the 10 most recent, no filters
func (q *Queries) GetRecentWorkspaces(ctx context.Context, arg GetRecentWorkspacesParams) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, getRecentWorkspaces, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.SceneJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, user_id, name, type, status, scene_json, created_at, updated_at FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.SceneJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspacesFiltered = `-- name: GetWorkspacesFiltered :many
SELECT id, user_id, name, type, status, scene_json, created_at, updated_at FROM workspaces
WHERE user_id = $1
  AND ($2::TEXT    IS NULL OR type   = $2::TEXT)
  AND ($3::TEXT  IS NULL OR status = $3::TEXT)
  AND ($4::TEXT  IS NULL OR name   ILIKE '%' || $4::TEXT || '%')
ORDER BY created_at DESC
LIMIT  $6
OFFSET $5
`

type GetWorkspacesFilteredParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	Type      pgtype.Text `json:"type"`
	Status    pgtype.Text `json:"status"`
	Search    pgtype.Text `json:"search"`
	OffsetVal int32       `json:"offset_val"`
	LimitVal  int32       `json:"limit_val"`
}

// Used on the library page — all filters optional, server-side pagination
func (q *Queries) GetWorkspacesFiltered(ctx context.Context, arg GetWorkspacesFilteredParams) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, getWorkspacesFiltered,
		arg.UserID,
		arg.Type,
		arg.Status,
		arg.Search,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.SceneJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces
SET
    name       = $2,
    status     = $3,
    scene_json = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, type, status, scene_json, created_at, updated_at
`

type UpdateWorkspaceParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Status    string    `json:"status"`
	SceneJson []byte    `json:"scene_json"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspace,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.SceneJson,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.SceneJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
