// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_models.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkspaceModel = `-- name: CreateWorkspaceModel :one
INSERT INTO workspace_models (workspace_id, user_id, name, s3_url, source)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, user_id, name, s3_url, source, created_at
`

type CreateWorkspaceModelParams struct {
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	UserID      uuid.UUID   `json:"user_id"`
	Name        pgtype.Text `json:"name"`
	S3Url       string      `json:"s3_url"`
	Source      string      `json:"source"`
}

func (q *Queries) CreateWorkspaceModel(ctx context.Context, arg CreateWorkspaceModelParams) (WorkspaceModel, error) {
	row := q.db.QueryRow(ctx, createWorkspaceModel,
		arg.WorkspaceID,
		arg.UserID,
		arg.Name,
		arg.S3Url,
		arg.Source,
	)
	var i WorkspaceModel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Name,
		&i.S3Url,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWorkspaceModel = `-- name: DeleteWorkspaceModel :exec
DELETE FROM workspace_models WHERE id = $1
`

func (q *Queries) DeleteWorkspaceModel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceModel, id)
	return err
}

const getWorkspaceModelByID = `-- name: GetWorkspaceModelByID :one
SELECT id, workspace_id, user_id, name, s3_url, source, created_at FROM workspace_models WHERE id = $1
`

func (q *Queries) GetWorkspaceModelByID(ctx context.Context, id uuid.UUID) (WorkspaceModel, error) {
	row := q.db.QueryRow(ctx, getWorkspaceModelByID, id)
	var i WorkspaceModel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Name,
		&i.S3Url,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceModelsByWorkspaceID = `-- name: GetWorkspaceModelsByWorkspaceID :many
SELECT id, workspace_id, user_id, name, s3_url, source, created_at FROM workspace_models
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetWorkspaceModelsByWorkspaceID(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceModel, error) {
	rows, err := q.db.Query(ctx, getWorkspaceModelsByWorkspaceID, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceModel
	for rows.Next() {
		var i WorkspaceModel
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Name,
			&i.S3Url,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
