// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_chats.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkspaceChat = `-- name: CreateWorkspaceChat :one
INSERT INTO workspace_chats (workspace_id, user_id, role, type, content, image_url, model_snapshot, job_id, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, workspace_id, user_id, role, type, content, image_url, model_snapshot, job_id, result_model_id, status, created_at
`

type CreateWorkspaceChatParams struct {
	WorkspaceID   uuid.UUID   `json:"workspace_id"`
	UserID        uuid.UUID   `json:"user_id"`
	Role          string      `json:"role"`
	Type          string      `json:"type"`
	Content       string      `json:"content"`
	ImageUrl      pgtype.Text `json:"image_url"`
	ModelSnapshot []byte      `json:"model_snapshot"`
	JobID         pgtype.Text `json:"job_id"`
	Status        pgtype.Text `json:"status"`
}

func (q *Queries) CreateWorkspaceChat(ctx context.Context, arg CreateWorkspaceChatParams) (WorkspaceChat, error) {
	row := q.db.QueryRow(ctx, createWorkspaceChat,
		arg.WorkspaceID,
		arg.UserID,
		arg.Role,
		arg.Type,
		arg.Content,
		arg.ImageUrl,
		arg.ModelSnapshot,
		arg.JobID,
		arg.Status,
	)
	var i WorkspaceChat
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.Type,
		&i.Content,
		&i.ImageUrl,
		&i.ModelSnapshot,
		&i.JobID,
		&i.ResultModelID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceChatsByWorkspaceID = `-- name: GetWorkspaceChatsByWorkspaceID :many
SELECT id, workspace_id, user_id, role, type, content, image_url, model_snapshot, job_id, result_model_id, status, created_at FROM workspace_chats
WHERE workspace_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetWorkspaceChatsByWorkspaceID(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceChat, error) {
	rows, err := q.db.Query(ctx, getWorkspaceChatsByWorkspaceID, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceChat
	for rows.Next() {
		var i WorkspaceChat
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.Type,
			&i.Content,
			&i.ImageUrl,
			&i.ModelSnapshot,
			&i.JobID,
			&i.ResultModelID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspaceChatStatus = `-- name: UpdateWorkspaceChatStatus :one
UPDATE workspace_chats
SET
    status          = $2,
    content         = $3,
    result_model_id = $4
WHERE id = $1
RETURNING id, workspace_id, user_id, role, type, content, image_url, model_snapshot, job_id, result_model_id, status, created_at
`

type UpdateWorkspaceChatStatusParams struct {
	ID            uuid.UUID   `json:"id"`
	Status        pgtype.Text `json:"status"`
	Content       string      `json:"content"`
	ResultModelID pgtype.UUID `json:"result_model_id"`
}

func (q *Queries) UpdateWorkspaceChatStatus(ctx context.Context, arg UpdateWorkspaceChatStatusParams) (WorkspaceChat, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceChatStatus,
		arg.ID,
		arg.Status,
		arg.Content,
		arg.ResultModelID,
	)
	var i WorkspaceChat
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.Type,
		&i.Content,
		&i.ImageUrl,
		&i.ModelSnapshot,
		&i.JobID,
		&i.ResultModelID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
